// Autogenerated by geninfo.sh, do not edit

package elec332.gregsprospecting2.main;

public class Info {
	static final String modName = "Greg's Prospecting";
	static final String modID = "GregsProspecting";
	static final String modPackage = "prospecting";
	static final String versionNumber = "1.6.1";
	static final String versionBounds = "[1.6,1.7)";
}
